### ISSUE TITLE
Images sent in Discord chat do not appear in Hubs chat

### ISSUE THREAD

**Issue by misslivirose** [MozillaReality/hubs-discord-bot#19]
If you upload an image to a Discord channel, the bot relays that someone has sent a message, but the image does not appear (it is an empty message).

**Comment by mqp** [comment]
Huh, you are right. I thought I made this work. I will figure out what the deal is.

**Comment by mqp** [comment]
Oh yeah, I sort of lost track of it and [didn't totally finish](https://github.com/mozilla/hubs/pull/1189). I will get this in this week.
