### ISSUE TITLE
Photos should be sent to Discord chat always

### ISSUE THREAD

**Issue by mqp** [MozillaReality/hubs-discord-bot#21]
Greg feels strongly that photos taken in Hubs should be sent to Discord without having to be pinned. I'm not so sure, but it seems fine.

**Comment by blairmacintyre** [comment]
I’m curious why things need to be pinned to get sent to discord.  I would have expected everything that gets added to hubs to go to discord.

**Comment by mqp** [comment]
You'll have to argue with @gfodor -- I agree with you, but there are two counterarguments:

1. It might seem like too much spam, depending on what you think people are getting out of the bridged information. At least you may want a deduplication, so that if you spawn several copies of something it doesn't get added several times. (We have this deduplication anyway.)
2. Apparently Mozilla legal is concerned that people clearly understand when they do something in Hubs that is going to get sent to Discord, and it's harder to figure out how to do that with a decent UX if our policy is to bridge every spawned item. (We can do it with pins by notifying people when they hover or click the pin button.)

**Comment by blairmacintyre** [comment]
These both seem pretty compelling.

I wonder if it could be a setting, from discord (“!hubs sendallonbjects”)
