### ISSUE TITLE
Feature: include room link in join message

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/hubs-discord-bot#7]
We should include some form of the room link in the join message so there's no visual disconnect between the join of a user (which is likely the first thing observers will see relevant to the discord bot in their community) and the actual CTA of being able to visit that person. Additionally, having the room link show up here will help overall with room link discovery for those who do not understand or notice that the link is in the topic. (Especially on mobile, the user will already have had to understand the link's availability in the topci to even know to look there.)

**Comment by mqp** [comment]
Still I do not like this in general, but I see your point about the CTA. Maybe when the first person joins the room after some inactivity, it should also echo information about the room into Discord?

**Comment by gfodor** [comment]
yeah perhaps a good compromise is to broadcast the room info when the room transitions from 0 to 1 users within a grace period. this is incidentally the same heuristic we use for sending a push notification, so perhaps we should just unify that somehow.

**Comment by gfodor** [comment]
it would arguably make sense for these to always be the same rule, if you assume sending this information is noisy. if we can avoid the unfurl, it seems non-noisy to include it in the join messages, so perhaps we would want both. (push notification rule results in a fully unfurled notification about the room, similar to the copy in the notifications we send, and separate from that we include a unfurled shortlink in the join messages.)
