### ISSUE TITLE
Feature: de-dupe media URLs

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/hubs-discord-bot#8]
Bot should probably only post a given media URL at most once over some period.

**Comment by mqp** [comment]
I agree with this, I thought that maybe pinning would make this not necessary but it's necessary for the "pin and re-pin to try to position stuff in the room" case. (Which to me is evidence that it is not good to conflate pinning with Discord broadcasting, but it's what we did.)

**Comment by gfodor** [comment]
the main thing happening here I think is just when people move pinned objects around in pause mode (which I heavily endorse as a good UX, tho it's controversial) it re-pins it, so results in spam. we could mitigate this more upstream somehow potentially but I don't feel strongly either way, beyond that it seems like it could get complicated if we do it elsewhere.

**Comment by mqp** [comment]
#12.
